### ISSUE TITLE
ember cli live reload default behavior

### ISSUE THREAD

**Issue by eccegordo** [ryanlabouve/ember-cli-randoport#1]
Cool addon thanks for making this.

Also you might be curious about this if you don't already know...

https://github.com/ember-cli/ember-cli/pull/4443

**Comment by ryanlabouve** [comment]
Sweet! Thanks for posting this.

**Comment by ryanlabouve** [comment]
@eccegordo used the same package that was used in the like you posted to ensure the port that is generated not being used.

Thanks again!
